### PR TITLE
Fixed Issue #1

### PR DESCRIPTION
**Pull request by Dhruv-Mahajan1**
@DarshitJain04 

Opening G-Form through the extension

https://user-images.githubusercontent.com/78262624/145076242-8750188a-9466-4c4e-8084-1120ce693b9e.mp4

Opening g -form not with the extension

https://user-images.githubusercontent.com/78262624/145076362-322d62f5-3fe6-441b-890b-6a41833e08d7.mp4

Earlier timer was getting injected in all g-forms irrespective of how it was being opened

PS:  [Vishal](https://github.com/VishalZ123)  helped me in this :)

### CODE REVIEW

**Comment by DarshitJain04** [comment]
- Are you using Eslint Prettier to format your code?
- Try to give better names to variables
- Try following Camel Case for variables

**Comment by DarshitJain04** [comment]
`Fixed Issue devlup-labs#1` Your commit message should indicate the changes you have pushed and not just the issue it is fixing

**Comment by Dhruv-Mahajan1** [comment]
No, I am not using  Eslint Prettier  to format 
sure, I will try to use better   variable names

**Comment by Dhruv-Mahajan1** [comment]
@DarshitJain04  I solved the issue by this:
I introduced a bool variable `ThroughTheExtension` and set its default value to `False`.
whenever the g-form is opened is through the extension input dialogue box   using `chrome storage api` I set its value to `True`.
Finally, I used an `If` statement to check if the `ThroughTheExtension`  if it is `True` render the react component i.e. `Timer` component

**Comment by Dhruv-Mahajan1** [comment]
Video file for the latest Commit:

https://user-images.githubusercontent.com/78262624/145277454-dd48381e-85ec-40c2-a392-300ef41ba87b.mp4

Input  Start Time:  `12/09/2021 01:38 PM`
Input  End Time :  `12/09/2021 01:48 PM`

`Time Difference :` 10 minutes

**Comment by DarshitJain04** [comment]
> No, I am not using Eslint Prettier to format sure, I will try to use better variable names

Then use these formatting tools. Create another PR and add the eslint and prettier configuration

**Comment by DarshitJain04** [comment]
> https://docs.google.com/forms/

The custom timer is not working properly
I added start time as 20:02 and end time as 20:03 [PS: I did this at 20:00 hours] and as soon as I clicked _Submit_, it opened the form. So basically it is not taking the time at which it needs to start into consideration

Secondly, add checks for proper start and end times. For example, the start time can not be before the current time and end time can not be before start time, etc.

**Pull request closed without merging**
