### PR TITLE
Added Timer

### PR DESCRIPTION
**Pull request by Dhruv-Mahajan1**
image
timer will appear when google form link is a input , it will be of fixed time

### CODE REVIEW

**Comment by Dhruv-Mahajan1** [comment]
@DarshitJain04   please review the PR 
thank you

**Comment by DarshitJain04** [comment]
Try to write better commit messages
`chck` is not an appropriate commit message

**Comment by DarshitJain04** [comment]
> image timer will appear when google form link is a input , it will be of fixed time

Instead of an image, maybe add a small demo video of the working timer?

**Comment by Dhruv-Mahajan1** [comment]
okay @DarshitJain04 I will keep these things in mind for future work 
Thank you

**Comment by Dhruv-Mahajan1** [comment]
@DarshitJain04  Here is the video for the same 

https://user-images.githubusercontent.com/78262624/144312296-d0f65f7c-4551-4547-aab9-b0f19a056fbe.mp4

**Review by DarshitJain04 — APPROVED** [review]

**Pull request merged**
